### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by ggreco77** [lpsinger/ligo-virgo-emfollowup-tutorial#3]
Great Tutorial!
I point out some problems at the following links.

**DS9** ---> No work (5. Working with probability sky maps)
**https://docs.python.org/3/glossary.html#term-decorator** ---> No work
**reprojection with GammaPy** ---> Old ---> http://reproject.readthedocs.org/en/latest/index.html
**~/.netrc** ---> No work

**Comment by lpsinger** [comment]
Sorry, what doesn't work?

**Comment by lpsinger** [comment]
Fixed. Some of those sites had reorganized their own structure.
