### ISSUE TITLE
Healpix contour plot function

### ISSUE THREAD

**Issue by ggreco77** [lpsinger/ligo-virgo-emfollowup-tutorial#4]
A paragraph that explains how to make contour plot in a Healpix skymap is recommended.
Even better a function that would do this with a single  command line 
based on _healpy.get_interp_val_.

Thanks,
Giuseppe

**Comment by lpsinger** [comment]
What a coincidence. I just wrote a [native HEALPix contouring algorithm](https://github.com/lpsinger/lalsuite/blob/bayestar_contour_allsky/lalinference/python/bayestar_contour_allsky.py) because I needed paths that had the correct topology regardless of map projection boundaries.

**Comment by ggreco77** [comment]
Great coincidence. The _bayestar_contour_allsky_ function is part of **LALInference**.
Can I use _pip_ to install such module?

**Comment by lpsinger** [comment]
No.

**Comment by ggreco77** [comment]
https://www.lsc-group.phys.uwm.edu/daswg/docs/howto/lal-install.html
for installing **LALSuite** software.

A version without the above dependency 
could be achieved by changing
         i) _prob, _ = fits.read_sky_map(infilename, nest=True)_ -->
            _prob = hp.read_map(infilename, nest=True)_
          ii) inclosing  _postprocess.py_ from
              http://software.ligo.org/docs/lalsuite/lalinference/postprocess_8py_source.html
          iii) and commenting the _Smooth_ option.
